### ISSUE TITLE
Testers wanted [$10]

### ISSUE THREAD

**Issue by velnias75** [velnias75/NetMauMau#1]
You like to play Mau Mau? So you can can combine fun and help at the same time.

**Comment by velnias75** [comment]
@gonzoid: Wouldn't that be a good task for you?
@3rdwiki: How do you want to decide if a tester can get the bounty? It won't generate to much code on **this** issue.
But *thank you a lot* for setting bounties on this an the other issues :smile:

**Comment by 3rdwiki** [comment]
@velnias75  Shhesh am I being irked for actually giving money ?

To answer your question - I'm on a chromebook.

**Comment by velnias75** [comment]
@3rdwiki so, you are **NOT** that *3rdwiki* from bountysource donating 30 $ to my project? :astonished:

**Comment by 3rdwiki** [comment]
no , I am but well what your community question ?

I am the prime funder of Ubuntu.

**Comment by velnias75** [comment]
Hm, if you don't want to test, you could use your influence to get NetMauMau from the PPA into the official distro :grinning:

**Comment by 3rdwiki** [comment]
That not gonna happen as I have no influence - at all.
As far as the Ubuntu distro on chromebooks  - I'm just a backer
I know all the stake holders, but they don't listen to me .

**Comment by velnias75** [comment]
So it seems you do something wrong.

But my project is perfect for chromebooks as well and is in need of 
hackers :grinning:

**Comment by 3rdwiki** [comment]
Where is it in the play store ?

**Comment by velnias75** [comment]
I thought you're a hacker?
You could adapt it to chromebook and finally add it into the play store.

**Comment by 3rdwiki** [comment]
No, just a guy with a wallet.
Surely, it's your task to approach google - add it as a bounty.

**Comment by velnias75** [comment]
In fact I'm happy at first if it runs well on various Linux distros and on the 
sorrowsome Winf*ck.

**Comment by 3rdwiki** [comment]
Is there a NetMauMau irc ?

**Comment by velnias75** [comment]
Currently one developer, less than 50 downloads on Sourceforge (Launchpad and 
OBS I cannot track unfortunately, no stars, 1 fork, almost no clones...)

NetMauMau suffers the fate of almost all new open source projects if **NOT** 
sponsored by the big players :sad:

=> no IRC

**Comment by 3rdwiki** [comment]
It's the little details that are vital. Little things make big things happen.

**Comment by velnias75** [comment]
My driving force is to have a project to develop. Without developing I'm missing something in my life.
To all anger of my family, declared haters of software engineers, because
* software is not being developed, it is growing on trees in Redmond and Cupertino
* the term *software developer* is an alias for something less than a secretary, a brainless person which is all the day just typing an clicking, while not being productive at all

But I **love** developing and if NetMauMau gets ignored (my family **loves** playing MauMau, but it is impossible to get them as testers, because they are additionally afraid to have at least 2 doctor degrees in computer science to be able to test it :angry:), it dosn't bother me.

So, it is out now :smile:

**Comment by 3rdwiki** [comment]
At the [moment](https://www.bountysource.com/issues/847738-allow-bounties-on-anything-after-the-fact) we cannnot give money for individual posts; if we could then I'd have shown you a fiverr ...

But you can always check the system to see what you like and give it the thumbs up; which by definition of the website actually means the thumbs down ( 'cos it's a bug) , but no-one ever talks about that.

**Comment by velnias75** [comment]
Hello @gonzoid,

No problem if you cannot do as much like me on the project. I have unfortunately no job (employees, read and see for yourself here in the repo :grin:), so I'm able to do so much.

*About the bounties:* it seems many people move their fingers only if they see :dollar: :cry: It is free to you to redonate your bounty on bountysource. I will do the same with my *reward* I got, because the donor maybe didn't saw I am assigned to that issue.

I have a move too, resp. I *have to* move to end of this month, but not yet any other place to stay. This will get troublesome too.

**Comment by velnias75** [comment]
Hello @gonzoid,

No problem if you cannot do as much like me on the project. I have unfortunately no job (employees, read and see for yourself here in the repo :grin:), so I'm able to do so much.

*About the bounties:* it seems many people move their fingers only if they see :dollar: :cry: It is free to you to redonate your bounty on bountysource. I will do the same with my *reward* I got, because the donor maybe didn't saw I am assigned to that issue.

I have a move too, resp. I *have to* move to end of this month, but not yet any other place to stay. This will get troublesome too.

**Comment by velnias75** [comment]
Nobody is willing to test -> NetMauMau is just useless crap and not worth to get too much effort in future?
