### ISSUE TITLE
Does not show the spades/clubs/diamonds/hearts pictures

### ISSUE THREAD

**Issue by jimazas** [velnias75/NetMauMau#18]
When a Jack(J) is thrown and you have to pick between the 4 colours with the pop up window, it displays only a black or red bar instead of the pictures of spade,clubs,diamonds and hearts. The same thing happens when the opponent throws a Jack(J) and it should display these pictures below the thrown cards.

**Comment by velnias75** [comment]
This issue was moved to velnias75/NetMauMau-Qt-Client#13
